### ISSUE TITLE
Request: Do you know of a good guide for creating a dataset?

### ISSUE THREAD

**Issue by deadman96385** [MontclairRobotics/DeepSpaceML#1]
We were looking into using tensorflow, but we had trouble even starting because we couldn't find tons of info on actually creating the model/dataset that is used by the python scripts. Just a bunch of take this model and use it which is obviously not good for our use case. Any info would be much appreciated.

**Comment by H1ppx** [comment]
@deadman96385 for tensorflow: the official tutorials for the keras model are on tensorflow's website. Another useful link was https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10. For this repository, we are switching to a yolo based model. Further information on that would be: https://pjreddie.com/darknet/.

**Comment by H1ppx** [comment]
@deadman96385 for tensorflow: the official tutorials for the keras model are on tensorflow's website. Another useful link was https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10. For this repository, we are switching to a yolo based model. Further information on that would be: https://pjreddie.com/darknet/.

Hope this help,
-Will

**Comment by deadman96385** [comment]
I appreciate the response, we will definitely look over this!
